ci(default*-bare): review workflow, variable, use molecule verify, more after step tests

diff --git a/.github/workflows/default-nosystemd-bare.yml b/.github/workflows/default-nosystemd-bare.yml
--- a/.github/workflows/default-nosystemd-bare.yml
+++ b/.github/workflows/default-nosystemd-bare.yml
@@ -13,20 +13,31 @@ jobs:
   build:
     permissions:
       contents: read
-    runs-on: ${{ matrix.os }}
+    runs-on: ubuntu-${{ matrix.version }}
+    continue-on-error: ${{ matrix.experimental }}
     strategy:
       fail-fast: false
       max-parallel: 4
       matrix:
-        os: [ubuntu-latest, ubuntu-20.04]
+        include:
+          - distribution: ubuntu
+            version: '24.04'
+            suite: default
+            experimental: false
+          - distribution: ubuntu
+            version: '22.04'
+            suite: default
+            experimental: false
     env:
       ANSIBLE_CALLBACKS_ENABLED: profile_tasks
       ANSIBLE_EXTRA_VARS: "-e osquery_systemd_restriction_enable=false"
+      ANSIBLE_ROLE: juju4.osquery
+      ANSIBLE_SUITE: ${{ matrix.suite }}
 
     steps:
       - uses: actions/checkout@v4
         with:
-          path: juju4.osquery
+          path: ${{ env.ANSIBLE_ROLE }}
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
@@ -42,7 +53,8 @@ jobs:
           ls -l /opt/hostedtoolcache/Python/3.9.1/x64/bin || true
           echo "/opt/hostedtoolcache/Python/3.9.1/x64/bin" >> $GITHUB_PATH
           ansible --version
-          cd $GITHUB_WORKSPACE/juju4.osquery
+          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE
+          [ -f molecule/$ANSIBLE_SUITE/requirements.yml ] && ansible-galaxy install -r molecule/$ANSIBLE_SUITE/requirements.yml
           [ -f get-dependencies.sh ] && sh -x get-dependencies.sh
           { echo '[defaults]'; echo 'callbacks_enabled = profile_tasks, timer'; echo 'roles_path = ../'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
       - name: Environment
@@ -55,30 +67,61 @@ jobs:
           find -ls
       - name: run test
         run: |
-          cd $GITHUB_WORKSPACE/juju4.osquery && ansible-playbook -i localhost, --connection=local --become -vvv molecule/default/converge.yml ${ANSIBLE_EXTRA_VARS}
+          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/$ANSIBLE_SUITE/converge.yml ${ANSIBLE_EXTRA_VARS}
         env:
           PY_COLORS: '1'
           ANSIBLE_FORCE_COLOR: '1'
       - name: idempotency run
         run: |
-          cd $GITHUB_WORKSPACE/juju4.osquery && ansible-playbook -i localhost, --connection=local --become -vvv molecule/default/converge.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 1)
-        continue-on-error: true
+          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/$ANSIBLE_SUITE/converge.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)
+      - name: verify
+        run: |
+          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/$ANSIBLE_SUITE/verify.yml ${ANSIBLE_EXTRA_VARS}
+        env:
+          PY_COLORS: '1'
+          ANSIBLE_FORCE_COLOR: '1'
       - name: On failure
         run: |
           systemctl -l --no-pager status
-        if: env.WORKFLOW_CONCLUSION == 'failure'  # notify only if failure
-      - name: After script - systemctl
+          systemctl -l --no-pager --failed
+          ls -l /usr/bin/ | egrep '(python|pip|ansible)'
+          pip freeze
+          pip3 freeze
+          ip addr
+          cat /etc/resolv.conf
+          host www.google.com
+          ping -c 1 www.google.com || true
+          ping -c 1 8.8.8.8 || true
+          ps axuw
+          netstat -anp
+        if: ${{ failure() }}
+        continue-on-error: true
+      - name: After script - ansible setup
         run: |
+          ansible -i inventory --connection=local -m setup localhost
+        if: ${{ always() }}
+        continue-on-error: true
+      - name: After script - systemd
+        run: |
+          systemctl -l --no-pager status osqueryd || true
           systemd-analyze security osqueryd || true
           systemctl --failed || true
           systemctl status osqueryd || true
         if: ${{ always() }}
         continue-on-error: true
+      - name: After script - files
+        run: |
+          dpkg -L osquery
+        if: ${{ always() }}
+        continue-on-error: true
       - name: After script - osquery
         run: |
+          set -x
           cat /etc/osquery/osquery.conf || true
-          osqueryi --config_dump --verbose
-          osqueryi --config_check --verbose
+          osqueryi --line "SELECT version, build, platform FROM os_version;" || true
+          osqueryi --line "SELECT version from osquery_info;" || true
+          osqueryi --config_dump --verbose || true
+          osqueryi --config_check --verbose || true
         if: ${{ always() }}
         continue-on-error: true
       - name: After script - osquery ERROR/WARNING/INFO
@@ -88,6 +131,9 @@ jobs:
         continue-on-error: true
       - name: After script - osquery results logs
         run: |
+          set -x
+          ls -lAF /var/log/osquery/
+          sudo head -10 /var/log/osquery/osqueryd.results.log
           sudo tail -100 /var/log/osquery/osqueryd.results.log
         if: ${{ always() }}
         continue-on-error: true
@@ -100,5 +146,14 @@ jobs:
       - name: After script - resulting systemd config
         run: |
           find /etc/systemd/system/osqueryd.service.d/ -type f -exec cat {} \;
+        if: ${{ always() }}
+        continue-on-error: true
+      - name: After script - apparmor
+        run: |
+          set -x
+          sudo grep -r "runbindable*/*" /etc/apparmor.d
+          sudo ls -l /etc/apparmor.d/usr.bin.osqueryd
+          sudo cat /etc/apparmor.d/usr.bin.osqueryd
+          dpkg -l | grep apparmor
         if: ${{ always() }}
         continue-on-error: true
